# Generated by Django 3.2 on 2021-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_property_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
