# Generated by Django 3.2 on 2021-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='emailstatus',
            field=models.CharField(default='NotSent', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='verifiedcost',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='verifiedimages',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='verifiedproperty',
            field=models.CharField(default='Not Verified', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='verifiedpropertydetails',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='verifiedvideos',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
