from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
    #path('home/',views.start,name="start"),
    path('dashboard/',views.dashboardView,name="dashboard"),
    path('dashboard/filters/',views.filtersView,name="filters"),
    path('dashboard/staffproperty/',views.staffProperty,name="staffproperty"),
    path('dashboard/staffproperty/<int:my_id>',views.staffpropertyDisplay,name="staffproperty_display"),
    path('dashboard/property/',views.propertyView,name="property"),
    path('dashboard/adpost/',views.adpostView,name="adpost"),
    path('dashboard/myprofile/',views.profileView,name="profile"),
    path('dashboard/myproperties/',views.myPropertiesView,name="myproperties"),
    path('dashboard/myfavourites/',views.favouritesView,name="myfavourites"),
    path('dashboard/myproperties/<int:my_id>',views.editProperty,name="edit_property"),
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
    path('logout/', views.logoutUser, name="logout"),  
    path('dashboard/property/<int:my_id>',views.propertyDisplay,name="property_display"),
    path('dashboard/property/favourite/<int:my_id>',views.propertyFavourite,name="property_favourite"),
    path('dashboard/property/owner/<int:my_id>',views.ownerDetails,name="owner_details"),
    path('dashboard/property/reviews/<int:my_id>',views.reviewsDisplay,name="reviews"),
    path('dashboard/property/reviewsowner/<int:my_id>',views.reviewsOwnerDisplay,name="reviewsowner"),
    path('dashboard/staffproperty/verification/<int:my_id>',views.verificationView,name="verification"),
    path('dashboard/about',views.aboutView,name="about"),
    path('dashboard/contact/<int:my_id>',views.contactView,name="contact"),
    path('dashboard/contact/',views.contactsupportView,name="contactsupport"), 
    path('dashboard/staffprofile/',views.profileStaffView,name="profilestaff"),
]